language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
      - debian-sid

before-script:
  - "sudo apt-get install cabal-install"
  - "cabal update"
  - "cabal install shellcheck"

script:
    - shellcheck -e SC2034 duplicity-backup.sh duplicity-backup.conf.example

matrix:
  fast_finish: true
